### ISSUE TITLE
"Configuration not registered"

### ISSUE THREAD

**Issue by mjsarfatti** [nordsoftware/lumen-doctrine#1]
Hello,
after following all instructions, including copying /lumen-doctrine/config/doctrine.php to /config, if I run **$ php artisan** I get the following:

```
  [Exception]                             
  Doctrine configuration not registered.  
```

Is it because I'm on Lumen 5.1, but this package was developed on 5.0?

**Comment by cniska** [comment]
In Lumen applications you need to register each configuration file manually in your `bootstrap/app.php` like so:

``` php
$app->configure('doctrine');
```
