### ISSUE TITLE
Cannot declare class EntityManager, because the name is already in use

### ISSUE THREAD

**Issue by felixdv** [nordsoftware/lumen-doctrine#17]
### What did you do?
Tried to run phpunit unit tests, but every test I want to run shows the following error:
```
1) UserTest::testCreateNewUser
ErrorException: Cannot declare class EntityManager, because the name is already in use

/src/vendor/nordsoftware/lumen-doctrine/src/DoctrineServiceProvider.php:68
/src/vendor/nordsoftware/lumen-doctrine/src/DoctrineServiceProvider.php:42
/src/vendor/laravel/lumen-framework/src/Application.php:174
/src/bootstrap/app.php:91
/src/tests/TestCase.php:15
/src/vendor/laravel/lumen-framework/src/Testing/TestCase.php:56
/src/vendor/laravel/lumen-framework/src/Testing/TestCase.php:67
/src/tests/TestCase.php:23
```

/src/tests/TestCase.php:23 contains this (in the `setUp()` method):
```php
parent::setUp();
```

/src/tests/TestCase.php:15 has this:
```php
return require __DIR__.'/../bootstrap/app.php';
```

I don't have this issue when using lumen-doctrine through the normal way (just requesting API calls), only when running unit tests.

### What versions of PHP, Lumen and this module are you using?
PHP 7.1.0, Lumen 5.3.3, lument-doctrine 2.4.1.

**Comment by hugovk** [comment]
This module doesn't contain unit tests yet. 

@felixdv Where did you run phpunit from?

**Comment by felixdv** [comment]
@hugovk I mean when I run unit tests in a project of mine that uses lumen-doctrine, not the tests from lumen-doctrine itself.

**Comment by Jalle19** [comment]
@felixdv hard to tell what's wrong without the source code for your application. Can you try to debug the issue yourself?

**Comment by hugovk** [comment]
@felixdv Ideally your unit tests would only be testing your own project, and not third-party code. Can you can mock and stub out third-party code?

**Comment by felixdv** [comment]
Basically, the `EntityManager` class already exists, so this piece of code (in your DoctrineServiceProvider.php) is going wrong:
```php
class_alias('Nord\Lumen\Doctrine\ORM\Facades\EntityManager', 'EntityManager');
```

I assume it has something to do with the order in which classes are loaded, but it's hard to find the exact cause.

**Comment by felixdv** [comment]
I've looked into this a bit more, and on http://stackoverflow.com/questions/30399766/where-to-register-facades-service-providers-in-lumen you can find someone (Peter Mellett) who has exactly the same issue. It is likely that `src/DoctrineServiceProvider.php` is somehow called multiple times when executing the unit tests, which breaks the `class_alias`.

Proof for this is that no matter which test it is, my first unit test always succeeds and only the subsequent unit tests fail.

I would propose wrapping the `class_alias` with a `class_exists` condition to fix this. I can create a PR for this if you want to.

**Comment by hugovk** [comment]
@felixdv Yes please, a PR would be great.
