### ISSUE TITLE
Use of dev version of packages in composer.json file

### ISSUE THREAD

**Issue by jaswdr** [nordsoftware/lumen-doctrine#4]
Hi, nice work with this package, is the some reason for using @dev version of doctrine in composer.json ?

**Comment by MarcFRICOU** [comment]
:+1: I can't even install dependencies 

```
 - nordsoftware/lumen-doctrine 2.2.0 requires doctrine/orm ~2.6@dev -> no matching package found.
```

**Comment by flyandi** [comment]
I had to fork it and add 2.5 to it since 2.6 is not in stable conditions yet.

**Comment by boedy** [comment]
@flyandi I've been trying all afternoon to load your fork via composer but it refuses to fetch it!

```
{
    "repositories":
    [
        {
            "url": "https://github.com/flyandi/lumen-doctrine.git",
            "type": "vcs"
        }
    ],
    "require": {
        "nordsoftware/lumen-doctrine": "dev-master"
    }
}
```

Any clue what I'm doing wrong here?

**Comment by cniska** [comment]
The reason why we use `@dev` is because this is still work in progress. However it is a central part of our REST API framework that we built on-top of Lumen so we will make it stable as soon as possible.

**Comment by jaswdr** [comment]
thanks for the response, but is not interesting have diferents branchs for
this ? one master who is stable and one development who have the most recent
features and fixes ?
@crisu83

**Comment by cniska** [comment]
@kryysler could you do the required changes?
